### ISSUE TITLE
Creation du Menu Cuisine

### ISSUE THREAD

**Issue by gaetan1903** [FoyerSociety/GFS#1]
### Création des pages statiques   

   - Tour de Cuisine 
   -  Menu Repas

**Comment by Landris18** [comment]
Le tour de cuisine miandry @rootkit7628 @ le scrooll view

**Comment by gaetan1903** [comment]
@Landris18  fa nga tsy efa vitan' ty commit ty le izy :
# # # cd44fe5

**Comment by rootkit7628** [comment]
@gaetan1903 IO juste le partie ambony fa le partie ambany mbola manahirana kely.

**Comment by Landris18** [comment]
Efa vita ty eee, ty preuve mipaka @ tenda 81b720f

**Comment by gaetan1903** [comment]
@Landris18  ary aiza le resaka scroll view ?

**Comment by Landris18** [comment]
@gaetan1903 efa najanona iny

**Comment by gaetan1903** [comment]
capture alternative oe ra mety ?

**Comment by gaetan1903** [comment]
![image](https://user-images.githubusercontent.com/43904633/99191447-d30a6080-277d-11eb-9295-c8143c9e4b66.png)


 ------------------------------------------------------------------------------------------------------------------------------


![image](https://user-images.githubusercontent.com/43904633/99191458-e61d3080-277d-11eb-8d85-92d151e2dc4c.png)

D'accord ,j'ai lancé ton commit 81b720f , ça fait l'affaire.

J'ai un petit problème d"encodage sous Windows , mais on verra plus tard.

Good Job Champion

**Comment by Landris18** [comment]
Oh yeah, tsara be izy zany, mais ce n'est que le commencement !!
