### ISSUE TITLE
Adresse à retenir 

### ISSUE THREAD

**Issue by gaetan1903** [FoyerSociety/GFS#11]
- Création du compte base de donné du foyer

- Interface graphique pour les débutants "phpMyAdmin"

- Site du serveur accessible via  : https://data.gaetanbot.xyz **à retenir par tout le monde** @Landris18  @rootkit7628 @Jayah001 

_Originally posted by @gaetan1903 in https://github.com/FoyerSociety/GFS-KivyMD/issues/7#issuecomment-728207984_

**Comment by gaetan1903** [comment]
Je fermerais cet issue lorsque vous auriez tous écris ici: "lu"

**Comment by Landris18** [comment]
lu

**Comment by rootkit7628** [comment]
lu

**Comment by Jayah001** [comment]
lu
