### ISSUE TITLE
MSpinner tsy afaka miova fotsy

### ISSUE THREAD

**Issue by Landris18** [FoyerSociety/GFS#12]
Tsy afaka miova fotsy mintsy ny Spinner, handeha hitaraina hanokatra issue @ Repo ny KivyMD mintsy za io.

**Comment by Landris18** [comment]
io zao nefa mandeh de bleu maitsomaitso zai lokony

![spinn](https://user-images.githubusercontent.com/47665507/99518230-58218f80-29a1-11eb-8828-3a7ebfe03006.png)

**Comment by gaetan1903** [comment]
Ataovy eto hoe lien an'io issue io , 

vo nanao mise a jour zan lery io ooo ?

**Comment by Landris18** [comment]
@gaetan1903  Ty ny lien https://github.com/kivymd/KivyMD/issues/673

Tsisy resaka mis à jour io fa mandeh nenaz io nefa efa nitesteko otranio kou nentsika ty fa tsy taf eee

**Comment by rootkit7628** [comment]
Fa nga tsy mety le bleu maintso teo ??

**Comment by rootkit7628** [comment]
@Landris18  efa vitako le izy 
I've change the color via the python file and it works
44ebf41
