### ISSUE TITLE
Proposition d'idée pour l'interface de création de tâche pour le grand ménage

### ISSUE THREAD

**Issue by Landris18** [FoyerSociety/GFS#14]
Mba mila hevitra avy @lisany za @ le pôziny le interface @le mi-assigné tâche @ grand ménage !! A retenir qu'il y 6 taches et 10 membres.

**Comment by rootkit7628** [comment]
Soit atao tableau avec nom de personne sy tache de checkbox na ataovy imagelist otrizao mba miova MDCard.
![image](https://user-images.githubusercontent.com/60097202/99533862-96c24480-29b7-11eb-954d-a3ed819020c9.png)

**Comment by rootkit7628** [comment]
sady  afaka asina rating io mba notena le qualitén'ny menage

**Comment by gaetan1903** [comment]
MDDialog lanaovana insertiona an donnée..

**Comment by gaetan1903** [comment]
@rootkit7628  sady chef de menage admin an'io 👍

**Comment by Landris18** [comment]
Efa nalefako 0d4376eb
