### ISSUE TITLE
MDRaisedButton tsy miova background_color 

### ISSUE THREAD

**Issue by Landris18** [FoyerSociety/GFS#16]
Ao @ le grand ménage igny za nampiasa MDRaisedButton de mba tiko ovaina le background fa tsy tafa nefa mba nijery docs officiels ihany.

**Comment by Landris18** [comment]
Reo menamena @tache reo manko bouton


![mena](https://user-images.githubusercontent.com/47665507/99697823-22fc6680-2aa1-11eb-87be-65b9e9fbb33b.png)

**Comment by rootkit7628** [comment]
Efa vita io le izy 
9a271e5
![image](https://user-images.githubusercontent.com/60097202/99763932-0138c900-2b0d-11eb-91a6-05c30cb998bb.png)

**Comment by Landris18** [comment]
Merci zandry 👏👏
