### ISSUE TITLE
Inona daolo mou ao anatin'le tableau transaction ?

### ISSUE THREAD

**Issue by Landris18** [FoyerSociety/GFS#19]
Ilaina maika !

**Comment by gaetan1903** [comment]
le fichier sql ao jerena ee eee

**Comment by gaetan1903** [comment]
https://github.com/FoyerSociety/GFS-KivyMD/issues/7#issuecomment-727747154 

date d'insertion an le donnee 
de le ray date simple an le zavatra natao, 

ça parrait un peu confus mais c'est different, 

Imaginons le scenario suivant:

bazary omaly , nefa androany vao nampidirin le admin tao 
azo tsik ny date nampidiran le admin azy moa azo tsika we vola t@ date ovina iny

**Comment by Landris18** [comment]
@gaetan1903  okay, mazava tsara izy zao

**Comment by Landris18** [comment]
Vita cd9dc60
