### ISSUE TITLE
Menu Ménage

### ISSUE THREAD

**Issue by gaetan1903** [FoyerSociety/GFS#2]
Page Statique 

- Tour de Ménage 
- Grand Ménage : 
     - Dispatche 
     - Date et Heure

**Comment by gaetan1903** [comment]
@Landris18 pourquoi ça traine ?

**Comment by rootkit7628** [comment]
Fini ! J'ai pas pu  faire le Dialog miediter grand menage en MDDropDownMenu donc je l'ai laissé avec le MDFieldText pour le moment
088c1d9
