### ISSUE TITLE
Cotisation

### ISSUE THREAD

**Issue by gaetan1903** [FoyerSociety/GFS#3]
Ajout Page Statique 

### Ajout cotisation repas en fonction année / mois

**Comment by gaetan1903** [comment]
@Landris18  Lorsequ'on travaille deçu , il faut que tu met le projet dans InProgress

**Comment by Landris18** [comment]
OK less, fa otran efa ho vita leizy

**Comment by Landris18** [comment]
Vita ty ka fermeko, rah misy zavatra tokony amboarina de afaka miteny: cd9dc60
