### ISSUE TITLE
Modélisation et Conception de données

### ISSUE THREAD

**Issue by gaetan1903** [FoyerSociety/GFS#7]
### Revoir Chaque fonctionnalité et Faire la conception 

-  Trouver la relation 
- Laisser de coté les indépendants 
- Rendre un schéma logique de données 

### Apres finalisation : 

- Creation du sql correspondant manuellement 
- Création base de donnée dans le Serveur

**Comment by rootkit7628** [comment]
J'ai fini la comception  de la base de donnée , c'est à Jayah maintenant de la créer ! Mais il reste encore la table pour le grand menage qui attend l'algorithme de Landry
![arleme](https://user-images.githubusercontent.com/60097202/99216623-2238ab80-27e7-11eb-976c-1206a6697564.jpg)

**Comment by gaetan1903** [comment]
ok GG 

exporteo le sql de atao anaty dossier model 

ataovy eto le commit rehefa vita

**Comment by gaetan1903** [comment]
- Création du compte base de donné du foyer

- Interface graphique pour les débutants "phpMyAdmin"

- Site du serveur accessible via  : https://data.gaetanbot.xyz **à retenir par tout le monde** @Landris18  @rootkit7628

**Comment by Jayah001** [comment]
@gaetan1903 1ère mission accomplie avec succès
création du script SQL pour la **BDD** entière 
exportation du fichier SQL dans _models/sql/_
###  f0867ba

**Comment by Landris18** [comment]
@Jayah001 Bienvenu poussin
