### ISSUE TITLE
Dynamisation du Login 

### ISSUE THREAD

**Issue by gaetan1903** [FoyerSociety/GFS#9]
- Backend du Login 
      - Insérer pour le test un User Admin dans la base
      - Pour faire simple, Hasher en *sha* le mot de passe
      

- Créer un argument *--prod*:
      - si préciser en lancement du script:  
              `Connection doit être faite avant login`
      - sinon: 
              `Passer sans login`

- Ajout d'un chargement durant la connexion

**Comment by rootkit7628** [comment]
@gaetan1903 je viens de finir la **connection au bdd avec le login** maintenant je m'occpe du test et le hash d67e122

**Comment by rootkit7628** [comment]
@Jayah001 Mba insereo vetivety le user Admin ao anaty bdd !! **Rapidement pls**

- [x] Insert data user

**Comment by Jayah001** [comment]
io eh f17c23f

**Comment by rootkit7628** [comment]
@gaetan1903  vita daoly le izy zfaa namoronako script "hashage.py" manao hashage ny mot de passe fa le micompare anle hash amin'ny login sisa atao de vita tanteraka !
@Jayah001 efa nitesteko t@n 'ny donnée admin le hash donc niova ny ao !
Pour preuve de mon travail acharné : 62495b7

**Comment by rootkit7628** [comment]
@Landris18 Efa nalefako any le chargement durant login fa anjaranla manova loko !
9b64220

**Comment by gaetan1903** [comment]
suite issue #12 

jereko le hashage, 

@rootkit7628  je te ferais un retour du travail acharnée

**Comment by gaetan1903** [comment]
Ok GG, 

Toute est OK maintenant 👍 🥇
